#!/bin/sh

fancy_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
}

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew ..."
      yes '' | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    export PATH="/usr/local/bin:$PATH"
else
  fancy_echo "Homebrew already installed. Skipping ..."
fi

brew_is_installed() {
  local name="$(brew_expand_alias "$1")"

  brew list -1 | grep -Fqx "$name"
}

brew_is_upgradable() {
  local name="$(brew_expand_alias "$1")"

  ! brew outdated --quiet "$name" >/dev/null
}

brew_install_or_upgrade() {
  if brew_is_installed "$1"; then
    if brew_is_upgradable "$1"; then
      fancy_echo "Upgrading %s ..." "$1"
      brew upgrade "$@"
    else
      fancy_echo "Already using the latest version of %s. Skipping ..." "$1"
    fi
  else
    fancy_echo "Installing %s ..." "$1"
    brew install "$@"
  fi
}

brew_expand_alias() {
  brew info "$1" 2>/dev/null | head -1 | awk '{gsub(/:/, ""); print $1}'
}

brew_tap() {
  brew tap "$1" 2> /dev/null
}

brew_tap 'caskroom/cask'
brew_install_or_upgrade 'brew-cask'
brew_install_or_upgrade 'git'
brew_install_or_upgrade 'fish'
brew_install_or_upgrade 'vim'
brew_install_or_upgrade 'wget'


brew cask install alfred
brew cask install atom
brew cask install cyberduck
brew cask install divvy
brew cask install docker
brew cask install evernote
brew cask install google-chrome
brew cask install microsoft-office
brew cask install steam
brew cask install unrarx
brew cask install vagrant
brew cask install virtualbox
brew cask install vmware-fusion
